# Generated by Django 5.1.4 on 2024-12-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_imagemodelhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodelhistory',
            old_name='user_image_query',
            new_name='user_image_prompt',
        ),
        migrations.RenameField(
            model_name='imagemodelhistory',
            old_name='user_text_query',
            new_name='user_text_prompt',
        ),
    ]
