# Generated by Django 5.1.4 on 2024-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_image_query_imagemodelhistory_user_image_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodelhistory',
            name='user_image_prompt',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
    ]
