# Generated by Django 5.1.4 on 2024-12-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_interactivechathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactivechathistory',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='interactivechathistory',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
