# Generated by Django 5.1.4 on 2024-12-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_interactivechathistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactivechathistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='interactivechathistory',
            name='updated',
        ),
    ]
