# Generated by Django 5.1.4 on 2024-12-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_qubevideomodelhistory_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qubeaudiomodelhistory',
            old_name='user_audio_prompt',
            new_name='user_audio',
        ),
        migrations.RenameField(
            model_name='qubeaudiomodelhistory',
            old_name='user_text_prompt',
            new_name='user_text',
        ),
    ]
