# Generated by Django 5.1.4 on 2024-12-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_qubecommunitymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qubecommunitymessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.qubecommunityroom'),
        ),
    ]
