# Generated by Django 5.1.4 on 2024-12-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_qubecommunityroom_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='qubecommunitymessage',
            name='user_visual_query',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
