# Generated by Django 5.1.4 on 2024-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_qubecommunitymessage_user_visual_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qubecommunitymessage',
            name='user_visual_query',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_image/'),
        ),
    ]
