# Generated by Django 5.1.4 on 2024-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_qubecommunitymessage_user_visual_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qubecommunityroom',
            name='host',
        ),
        migrations.RemoveField(
            model_name='qubecommunityroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='qubecommunityroom',
            name='topic',
        ),
        migrations.DeleteModel(
            name='qubeCommunityMessage',
        ),
        migrations.DeleteModel(
            name='qubeCommunityRoom',
        ),
        migrations.DeleteModel(
            name='qubeCommunityTopic',
        ),
    ]
