# Generated by Django 5.1.4 on 2024-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_message_user_visual_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_visual_query',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
