# Generated by Django 5.1.4 on 2024-12-25 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_chatuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatUser',
            new_name='ChatUserModel',
        ),
    ]
