# Generated by Django 5.1.4 on 2024-12-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_chatuser_chatusermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qubePredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text_prompt', models.TextField(max_length=250)),
                ('user_prediction_model1', models.TextField()),
                ('user_prediction_model2', models.TextField()),
                ('user_input_file', models.FileField(upload_to='uploaded_file/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='ChatUserModel',
        ),
    ]
